Add changes check in github action

diff --git a/.github/workflows/checks.yaml b/.github/workflows/checks.yaml
--- a/.github/workflows/checks.yaml
+++ b/.github/workflows/checks.yaml
@@ -21,6 +21,35 @@ jobs:
           version: v2.0.2
           args: --timeout 5m
 
+  check-uncommitted-changes:
+    name: Check uncommitted changes
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v4
+
+      - uses: actions/setup-go@v5
+        with:
+          go-version-file: go.mod
+
+      - name: Generate code
+        run: |
+          go generate ./...
+          make all
+
+      # Fails if any generated files is different from what is commited
+      - name: Checks uncommitted changes to generated files
+        run: |
+          changes=$(git status --porcelain)
+          if [[ -z $changes ]];
+          then
+            echo "No uncommitted changes to generated files"
+          else
+            echo "Error : there are uncommitted changes to generated files :"
+            echo "$changes"
+            exit 1
+          fi
+
   test:
     name: Test
     runs-on: ubuntu-latest
